function net = initializeTexturesCNN_2()

f=1/100 ;
net.layers = {} ;
% Imput capa 1: 128x128 
net.layers{end+1} = struct('type', 'conv', ...
                           'filters', f*randn(15,15,1,20, 'single'), ...
                           'biases', zeros(1, 20, 'single'), ...
                           'stride', 1, ...
                           'pad', 0) ;
% Imput capa 2: 114x114x20 
net.layers{end+1} = struct('type', 'pool', ...
                           'method', 'max', ...
                           'pool', [2 2], ...
                           'stride', 2, ...
                           'pad', 0) ;
% Imput capa 3: 57x57x20 
net.layers{end+1} = struct('type', 'conv', ...
                           'filters', f*randn(14,14,20,50, 'single'),...
                           'biases', zeros(1,50,'single'), ...
                           'stride', 1, ...
                           'pad', 0) ;
% Imput capa 4: 44x44x50 
net.layers{end+1} = struct('type', 'pool', ...
                           'method', 'max', ...
                           'pool', [2 2], ...
                           'stride', 2, ...
                           'pad', 0) ;
% Imput capa 5: 22x22x50 
net.layers{end+1} = struct('type', 'conv', ...
                           'filters', f*randn(13,13,50,100, 'single'),...
                           'biases', zeros(1,100,'single'), ...
                           'stride', 1, ...
                           'pad', 0) ;
% Imput capa 6: 10x10x100 
net.layers{end+1} = struct('type', 'pool', ...
                           'method', 'max', ...
                           'pool', [2 2], ...
                           'stride', 2, ...
                           'pad', 0) ;
% Imput capa 7: 5x5x100 
net.layers{end+1} = struct('type', 'relu') ;
% Imput capa 8: 5x5x100 
net.layers{end+1} = struct('type', 'conv', ...
                           'filters', f*randn(5,5,100,25, 'single'),...
                           'biases', zeros(1,25,'single'), ...
                           'stride', 1, ...
                           'pad', 0) ;
% Imput capa 9: 1x1x25 
net.layers{end+1} = struct('type', 'softmaxloss') ;
